name = "piirz-portfolio-api"
main = "src/index.js"
compatibility_date = "2024-12-01"

[[routes]]
pattern = "go.piirz.eu/*"
custom_domain = true

[vars]
ADMIN_USER = "admin"
# Set ADMIN_PASS via `wrangler secret put ADMIN_PASS`

[[kv_namespaces]]
binding = "LOGS"
id = "3f9dcc6165514a43a5698b15ea1c75b8"

[[kv_namespaces]]
binding = "PRODUCTS"
id = "51f01ec809c644e4a465c5489950e6cc"

[[r2_buckets]]
binding = "ATTACHMENTS"
bucket_name = "piirz-attachments"
